### ISSUE TITLE
Events showing in event list after start date

### ISSUE THREAD

**Issue by kcristiano** [agh1/civievent-widget#2]
CiviEvent widget for "Upcoming Events" is displaying events that have already started. 

I believe that it is supposed to only display events that have not yet started,  This site has classes that start on say Sept 5th and go until Dec 5th.  Registration closes before the first date of the class.  However, the evenst are still showing after the start date.  

You can see an example here: https://www.communitycenter.org.tw/

Wondering if we could also not display events where registration is closed as that could resolve this situation.

**Comment by agh1** [comment]
For better or worse, the widget uses the same list of events from the "Current and Upcoming Events" page in CiviCRM (linked from the events dash).  It's what you get if you follow the "View all" link when it's enabled.

On your example site, you can see the currently-running events there [on the big listing page](https://www.communitycenter.org.tw/civicrm/?page=CiviCRM&q=civicrm/event/ical&reset=1&list=1&html=1)

I can see the logic of suppressing events you can no longer register for, especially if they're in progress, and even more so if they won't end for months.

However, CiviCRM's event listing feeds take the opposite reasoning: if an event is closed to new registrations, you might still want to see the details so you know where/when it is.  That's even if you're running late and it started 5 minutes ago.

I don't want to change the default behavior from what CiviCRM does, but this does highlight the need for more flexible configuration options besides the "advanced" mode, which is rather rough.

**Comment by kcristiano** [comment]
Understood, I looked at the Custom API feature, but I can't find a field that will do what we need it to - at least not for these long running 'events'.

Thanks for the comments.
