### ISSUE TITLE
Add Event type is filter for event listing on standard output

### ISSUE THREAD

**Issue by sunilpawar** [agh1/civievent-widget#4]
Currently event type filter only available on custom filter, but then we have to re-work on custom display.
If want to just restrict the event listing with standard output using event type, then we can add additional parameters for event type id.

e.g
[civievent_widget event_type_id=3]

[civievent_widget event_type_id=1]

This way it only to specific event type without doing custom filter and display.

**Comment by sunilpawar** [comment]
https://github.com/agh1/civievent-widget/pull/3

**Comment by agh1** [comment]
Thanks again for opening the pull request.  For version 3.2 I applied that to the single event shortcode and added UI for both widgets to do this.
